---
- name: LEMP setup
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Install packages
      apt: 
        name: "{{ item }}" 
        state: present
      loop:
        - nginx
        - php8.1
        - php8.1-cli
        - php8.1-common
        - php8.1-mysql
        - php8.1-zip
        - php8.1-gd
        - php8.1-mbstring
        - php8.1-curl
        - php8.1-xml
        - php8.1-bcmath
        - php8.1-fpm
        - mysql-server
        - zip
        - unzip
        - git

    - name: Download composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Install composer
      shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
      loop:
        - /var/www/html/storage/framework/sessions
        - /var/www/html/storage/framework/views
        - /var/www/html/storage/framework/cache
        - /var/www/html/storage/logs

    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - php8.1-fpm
...

